---
# @tag docker-container-prereq-all:description: Ensure all pre-requisites are installed
# @tag docker-container-prereq-dependencytrack:description: Ensure all pre-requisites for dependencytrack are installed
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/prereq.yml"
  tags:
    - docker-container-prereq-all
    - docker-container-prereq-dependencytrack

# @tag docker-container-restore-all:description: Run restic restore for all restic enabled containers.
# @tag docker-container-restore-dependencytrack:description: Run restic restore for dependencytrack if restic is enabled.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/restore.yml"
  tags:
    - never
    - docker-container-restore-all
    - docker-container-restore-dependencytrack
  when:
    - docker_container_dependencytrack_restic_enable

# @tag docker-container-setup-all:description: Run setup task for all containers.
# @tag docker-container-setup-dependencytrack:description: Run setup task for dependencytrack.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup.yml"
  tags:
    - docker-container-setup-all
    - docker-container-setup-dependencytrack
    - docker-container-restore-all
    - docker-container-restore-dependencytrack

# @tag docker-container-backup-init-all:description: Run init backup task for all container.
# @tag docker-container-backup-init-dependencytrack:description: Run init backup task for dependencytrack if restic is enabled.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup_init.yml"
  tags:
    - docker-container-setup-all
    - docker-container-setup-dependencytrack
    - docker-container-backup-init-all
    - docker-container-backup-init-dependencytrack
  when:
    - docker_container_dependencytrack_restic_enable

# @tag docker-container-remove-all:description: Remove all containers.
# @tag docker-container-remove-dependencytrack:description: Remove dependencytrack.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/remove.yml"
  tags:
    - never
    - docker-container-remove-all
    - docker-container-remove-dependencytrack
    - docker-container-purge-all
    - docker-container-purge-dependencytrack

# @tag docker-container-purge-all:description: Remove all containers and delete volume mounts.
# @tag docker-container-purge-dependencytrack:description: Remove dependencytrack and delete volume mounts.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/purge.yml"
  tags:
    - never
    - docker-container-purge-all
    - docker-container-purge-dependencytrack

# @tag docker-container-backup-all:description: Backup all containers' volume mounts.
# @tag docker-container-backup-dependencytrack:description: Backup dependencytrack volume mounts.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup.yml"
  tags:
    - never
    - docker-container-backup-all
    - docker-container-backup-dependencytrack
  when:
    - docker_container_dependencytrack_restic_enable

# @tag docker-container-backup-list-all:description: List all containers' backups.
# @tag docker-container-backup-list-dependencytrack:description: List dependencytrack backups.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup_list.yml"
  tags:
    - never
    - docker-container-backup-list-all
    - docker-container-backup-list-dependencytrack
  when:
    - docker_container_dependencytrack_restic_enable
