---
# tasks file for ansible-role-docker-container-dependencytrack

- name: docker_container - {{ docker_container_dependencytrack_volume_dir }}
  ansible.builtin.file:
    path: "{{ docker_container_dependencytrack_volume_dir }}/{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "755"
  loop:
    - "data"

- name: docker_image pull {{ docker_image_dependencytrack_db_name }}
  community.docker.docker_image:
    name: '{{ docker_image_dependencytrack_db_name }}'
    force_source: true
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_dependencytrack_db_pull

- name: docker_image pull {{ docker_image_dependencytrack_apiserver_name }}
  community.docker.docker_image:
    name: '{{ docker_image_dependencytrack_apiserver_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_dependencytrack_apiserver_pull

- name: docker_image pull {{ docker_image_dependencytrack_frontend_name }}
  community.docker.docker_image:
    name: '{{ docker_image_dependencytrack_frontend_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_dependencytrack_frontend_pull



- name: docker_network {{ docker_container_dependencytrack_name }}
  community.docker.docker_network:
    name: "{{ docker_network_dependencytrack_name }}"
    driver: "{{ docker_network_dependencytrack_driver | default('bridge') }}"
    attachable: "{{ docker_network_dependencytrack_attachable | default(true) }}"
    enable_ipv6: "{{ docker_network_dependencytrack_enable_ipv6 | default(false) }}"
    internal: "{{ docker_network_dependencytrack_internal | default(false) }}"
    state: present

- name: docker_container {{ docker_container_dependencytrack_db_name }}
  community.docker.docker_container:
    name: "{{ docker_container_dependencytrack_db_name }}"
    comparisons: "{{ docker_container_dependencytrack_db_comparisons }}"
    image: "{{ docker_container_dependencytrack_db_image }}"
    state: "{{ docker_container_dependencytrack_db_state | default('started') }}"
    recreate: "{{ docker_container_dependencytrack_db_recreate | default(false) }}"
    restart: "{{ docker_container_dependencytrack_db_restart | default(false) }}"
    restart_policy: "{{ docker_container_dependencytrack_db_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_dependencytrack_db_auto_remove | default(false) }}"
    detach: "{{ docker_container_dependencytrack_db_detach | default(true) }}"
    init: "{{ docker_container_dependencytrack_db_init | default(false) }}"
    interactive: "{{ docker_container_dependencytrack_db_interactive | default(false) }}"
    keep_volumes: "{{ docker_container_dependencytrack_db_keep_volumes | default(true) }}"
    memory: "{{ docker_container_dependencytrack_db_memory | default('0') }}"
    paused: "{{ docker_container_dependencytrack_db_paused | default(false) }}"
    privileged: "{{ docker_container_dependencytrack_db_privileged | default(false) }}"
    read_only: "{{ docker_container_dependencytrack_db_read_only | default(false) }}"
    tty: "{{ docker_container_dependencytrack_db_tty | default(false) }}"
    env_file: "{{ docker_container_dependencytrack_db_env_file | default(omit) }}"
    env: "{{ docker_container_dependencytrack_db_env | default(omit) }}"
    volumes: "{{ docker_container_dependencytrack_db_volumes | default(omit) }}"
    labels: "{{ docker_container_dependencytrack_db_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_dependencytrack_db_networks_cli_compatible | default(true) }}"
    network_mode: "{{ docker_network_dependencytrack_db_name }}"
    pull: "{{ docker_container_dependencytrack_db_pull | default(false) }}"
    networks: "{{ docker_container_dependencytrack_db_networks }}"
    published_ports: "{{ docker_container_dependencytrack_db_ports | default(omit) }}"

- name: docker_container {{ docker_container_dependencytrack_apiserver_name }}
  community.docker.docker_container:
    name: "{{ docker_container_dependencytrack_apiserver_name }}"
    comparisons: "{{ docker_container_dependencytrack_apiserver_comparisons }}"
    image: "{{ docker_container_dependencytrack_apiserver_image }}"
    state: "{{ docker_container_dependencytrack_apiserver_state | default('started') }}"
    recreate: "{{ docker_container_dependencytrack_apiserver_recreate | default(false) }}"
    restart: "{{ docker_container_dependencytrack_apiserver_restart | default(false) }}"
    restart_policy: "{{ docker_container_dependencytrack_apiserver_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_dependencytrack_apiserver_auto_remove | default(false) }}"
    detach: "{{ docker_container_dependencytrack_apiserver_detach | default(true) }}"
    init: "{{ docker_container_dependencytrack_apiserver_init | default(false) }}"
    interactive: "{{ docker_container_dependencytrack_apiserver_interactive | default(false) }}"
    keep_volumes: "{{ docker_container_dependencytrack_apiserver_keep_volumes | default(true) }}"
    memory: "{{ docker_container_dependencytrack_apiserver_memory | default('0') }}"
    paused: "{{ docker_container_dependencytrack_apiserver_paused | default(false) }}"
    privileged: "{{ docker_container_dependencytrack_apiserver_privileged | default(false) }}"
    read_only: "{{ docker_container_dependencytrack_apiserver_read_only | default(false) }}"
    tty: "{{ docker_container_dependencytrack_apiserver_tty | default(false) }}"
    env_file: "{{ docker_container_dependencytrack_apiserver_env_file | default(omit) }}"
    env: "{{ docker_container_dependencytrack_apiserver_env | default(omit) }}"
    volumes: "{{ docker_container_dependencytrack_apiserver_volumes | default(omit) }}"
    labels: "{{ docker_container_dependencytrack_apiserver_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_dependencytrack_apiserver_networks_cli_compatible | default(true) }}"
    network_mode: "{{ docker_network_dependencytrack_apiserver_name }}"
    pull: "{{ docker_container_dependencytrack_apiserver_pull | default(false) }}"
    networks: "{{ docker_container_dependencytrack_apiserver_networks }}"
    published_ports: "{{ docker_container_dependencytrack_apiserver_ports | default(omit) }}"

- name: docker_container {{ docker_container_dependencytrack_frontend_name }}
  community.docker.docker_container:
    name: "{{ docker_container_dependencytrack_frontend_name }}"
    comparisons: "{{ docker_container_dependencytrack_frontend_comparisons }}"
    image: "{{ docker_container_dependencytrack_frontend_image }}"
    state: "{{ docker_container_dependencytrack_frontend_state | default('started') }}"
    recreate: "{{ docker_container_dependencytrack_frontend_recreate | default(false) }}"
    restart: "{{ docker_container_dependencytrack_frontend_restart | default(false) }}"
    restart_policy: "{{ docker_container_dependencytrack_frontend_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_dependencytrack_frontend_auto_remove | default(false) }}"
    detach: "{{ docker_container_dependencytrack_frontend_detach | default(true) }}"
    init: "{{ docker_container_dependencytrack_frontend_init | default(false) }}"
    interactive: "{{ docker_container_dependencytrack_frontend_interactive | default(false) }}"
    keep_volumes: "{{ docker_container_dependencytrack_frontend_keep_volumes | default(true) }}"
    memory: "{{ docker_container_dependencytrack_frontend_memory | default('0') }}"
    paused: "{{ docker_container_dependencytrack_frontend_paused | default(false) }}"
    privileged: "{{ docker_container_dependencytrack_frontend_privileged | default(false) }}"
    read_only: "{{ docker_container_dependencytrack_frontend_read_only | default(false) }}"
    tty: "{{ docker_container_dependencytrack_frontend_tty | default(false) }}"
    env_file: "{{ docker_container_dependencytrack_frontend_env_file | default(omit) }}"
    env: "{{ docker_container_dependencytrack_frontend_env | default(omit) }}"
    volumes: "{{ docker_container_dependencytrack_frontend_volumes | default(omit) }}"
    labels: "{{ docker_container_dependencytrack_frontend_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_dependencytrack_frontend_networks_cli_compatible | default(true) }}"
    network_mode: "{{ docker_network_dependencytrack_frontend_name }}"
    pull: "{{ docker_container_dependencytrack_frontend_pull | default(false) }}"
    networks: "{{ docker_container_dependencytrack_frontend_networks }}"
    published_ports: "{{ docker_container_dependencytrack_frontend_ports | default(omit) }}"
